# This Playbook contains test scenario for Create, modify, restart, release RDS instance and changing rds instance type, create and delete database , granting account permission and revoking acccount permission
# Playbook created by : 

- name: Testing  Create, modify, restart, release RDS instance and changing rds instance type, create and delete database , granting account permission and revoking acccount permission
  hosts: localhost
  connection: local
  vars:
#create rds instance     
    region: cn-beijing
    zone: 
    db_engine: MySQL 
    engine_version: 5.6
    db_instance_class: rds.mysql.s1.small
    db_instance_storage: 5
    instance_net_type: Intranet
    instance_description: test_desc
    security_ip_list: 192.168.0.0
    pay_type: Postpaid
    used_time: 
    connection_mode: Safe  
    instance_network_type: Classic
 #   vpc_id: vpc-2zermg3z16azq6iy4l70h
 #   vswitch_id: vsw-2zenp6eyukzkuriguwlwn
    private_ip_address:
    allocate_public_ip: true 
    public_connection_string_prefix: testconnstring
    public_port: 3306	
    maint_window: 22:00Z-02:00Z
    preferred_backup_time: 22:00Z-23:00Z
    preferred_backup_period: Monday,Tuesday 
    backup_retention_period: 12
    wait: no
    wait_timeout: 20
    db_tags:	
      name: akash
#create database
    db_name: testdatabase
    db_description: test
    character_set_name: utf8 
#create account
    account_name: testaccount
    account_password: test@123
    description: 
    account_type: Normal
    account_privilege: ReadOnly

  tasks:
    - name: create rds instance
      rds:
        region: '{{ region }}'
        zone: '{{ zone }}'
        command: create
        db_engine: '{{ db_engine }}'
        engine_version: '{{ engine_version }}'
        db_instance_class: '{{ db_instance_class }}'
        db_instance_storage: '{{ db_instance_storage }}'		
        instance_net_type: '{{ instance_net_type }}'
        instance_description: '{{ instance_description }}'
        security_ip_list: '{{ security_ip_list }}'
        pay_type: '{{ pay_type }}'
        used_time: '{{ used_time }}'    
        connection_mode: '{{ connection_mode }}'
        instance_network_type: '{{ instance_network_type }}'        
 #       vpc_id: '{{ vpc_id }}'
#        vswitch_id: '{{ vswitch_id }}'
        private_ip_address:
        allocate_public_ip: '{{ allocate_public_ip }}'
        public_connection_string_prefix: '{{ public_connection_string_prefix }}'
        public_port: '{{ public_port }}'
#        db_name: '{{ db_name }}'    
 #       db_description: '{{ db_description }}'
#        character_set_name: '{{ character_set_name }}'
        maint_window: '{{ maint_window }}'
        preferred_backup_time: '{{ preferred_backup_time }}'
        preferred_backup_period: '{{ preferred_backup_period }}'
        backup_retention_period: '{{ backup_retention_period }}'
        db_tags: '{{ db_tags }}'
        wait: '{{ wait }}'
        wait_timeout: '{{ wait_timeout }}'
      register: result_create_rds_instance
    - debug: var=result_create_rds_instance
    - debug: var=result_create_rds_instance.result[0].DBInstanceId

    - name: create account
      rds_acc_mgmt:
        region: '{{ region }}'
        command: create
        db_instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        account_name: '{{ account_name }}'
        account_password: '{{ account_password }}'
        description: '{{ description }}'
        account_type: '{{ account_type }}'
      register: result_create_account
    - debug: var=result_create_account

    - pause:
        seconds: 30

    - name: Create Database
      rds:
        region: '{{ region }}'
        command: create
        instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        db_name: '{{ db_name }}'
        db_description: '{{ db_description }}'
        character_set_name: '{{ character_set_name }}'
      register: create_database
    - debug: var=create_database

    - pause:
        seconds: 30

    - name: changing rds instance type
      rds:
        region: '{{ region }}'
        command: modify
        instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        db_instance_class: '{{ db_instance_class }}'
        db_instance_storage: '{{ db_instance_storage }}'
        pay_type: '{{ pay_type }}'
      register: result_changing_rds_instance_type
    - debug: var=result_changing_rds_instance_type

    - pause:
        seconds: 40

    - name: granting account permission
      rds_acc_mgmt:
        region: '{{ region }}'
        command: grant
        db_instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        db_name: '{{ db_name }}'
        account_name: '{{ account_name }}'
        account_privilege: '{{ account_privilege }}'
      register: result_grant_permission
    - debug: var=result_grant_permission

    - pause:
        seconds: 20    

    - name: revoking account permission
      rds_acc_mgmt:
        region: '{{ region }}'
        command: revoke
        db_instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        db_name: '{{ db_name }}'
        account_name: '{{ account_name }}'
      register: result_revoke_permission
    - debug: var=result_revoke_permission 

    - pause:
        seconds: 20  
    - name: modify rds instance
      rds:
        region: '{{ region }}'
        command: modify
        instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        db_instance_class: '{{ db_instance_class }}'
        db_instance_storage: '{{ db_instance_storage }}'		        
        instance_description: '{{ instance_description }}'
        security_ip_list: '{{ security_ip_list }}'
        pay_type: '{{ pay_type }}'      
        #connection_mode: '{{ connection_mode }}'
 #      instance_network_type: Classic
        #vpc_id: '{{ vpc_id }}'
        #vswitch_id: '{{ vswitch_id }}'
        #current_connection_string: '{{ current_connection_string }}'
        #connection_string_prefix: '{{ connection_string_prefix }}'
        #port: '{{ port }}'
        maint_window: '{{ maint_window }}'
        preferred_backup_time: '{{ preferred_backup_time }}'
        preferred_backup_period: '{{ preferred_backup_period }}'
        backup_retention_period: '{{ backup_retention_period }}'
      register: result_modify_rds_instance
    - debug: var=result_modify_rds_instance

    - pause:
        seconds: 40

    - name: Resetting Instance Password
      rds_acc_mgmt:
        region: '{{ region }}'
        command: reset_password
        db_instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        account_name: '{{ account_name }}'
        account_password: '{{ account_password }}'     
      register: resetting_instance_password
    - debug: var=resetting_instance_password


    - name: delete account
      rds_acc_mgmt:
        region: '{{ region }}'
        command: delete
        db_instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'
        account_name: '{{ account_name }}'
      register: result_delete_account
    - debug: var=result_delete_account

    - pause:
        seconds: 20

    - name: Restart rds instance
      rds:
        region: '{{ region }}'
        command: reboot
        instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'   
      register: restart_instance
    - debug: var=restart_instance
    
    - pause:
        seconds: 70

    - name: Release rds instance
      rds:
        region: '{{ region }}'
        command: delete
        instance_id: '{{ result_create_rds_instance.result[0].DBInstanceId }}'   
      register: release_instance
    - debug: var=release_instance


    
